# Generated by Django 4.0.3 on 2022-03-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pictue', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('bio', models.TextField()),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'Engineering'), ('CS', 'Computing'), ('HT', 'Health'), ('BS', 'Business'), ('ST', 'Sports'), ('OT', 'Other')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
