# Generated by Django 4.0.3 on 2022-03-28 12:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'Engineering'), ('CS', 'Computing'), ('HT', 'Health'), ('BS', 'Business'), ('ST', 'Sports'), ('OT', 'Other')], max_length=100),
        ),
    ]
