# Generated by Django 4.0.3 on 2022-03-28 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_profile_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENG', 'Engineering'), ('CS', 'Computing'), ('HT', 'Health'), ('BS', 'Business'), ('ST', 'Sports'), ('OT', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tag',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100, unique=True)),
                ('post_sb_title', models.CharField(blank=True, max_length=100)),
                ('post_url_slug', models.SlugField(max_length=100, unique=True)),
                ('post_body', models.TextField()),
                ('post_meta_description', models.TextField(blank=True, max_length=100)),
                ('post_date_created', models.DateTimeField(auto_now_add=True)),
                ('post_modified', models.DateTimeField(auto_now=True)),
                ('post_published_date', models.DateTimeField(blank=True, null=True)),
                ('post_published_status', models.BooleanField(default=False)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ManyToManyField(default='Random', to='account.category')),
            ],
            options={
                'ordering': ['post_published_date'],
            },
        ),
    ]
